services:
  - type: web
    name: md-bot
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: RENDER
        value: "true"
      - key: MORNING_SHEET_ID
        sync: false
      - key: EVENING_SHEET_ID
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
